### ISSUE TITLE
NFT with some traits exceptions 

### ISSUE THREAD

**Issue by Icus101** [Solseum/solseum-nft-generator#10]
Please how can i modify the code such that i can create an exception while layering and randomizing the traits such that one particular  traits should not be matched with another particular  traits

**Comment by Solseum** [comment]
The generator isnt optimized for that :(. It can be done with code but isnt simple to explain

**Comment by seuaCoder** [comment]
any hack for that ?

**Comment by Solseum** [comment]
Sup! No with this generator. Im creating a second version that is waaaay more optimized, faster that any other and with a lot of features
