### ISSUE TITLE
 images do not match

### ISSUE THREAD

**Issue by lucastoian** [Solseum/solseum-nft-generator#12]
i am using this command `python main.py -p 3` to generate 3 nft.
I recive this error:
` return im1._new(core.alpha_composite(im1.im, im2.im))
ValueError: images do not match`

What is the problem? The images has the same size and they are all png.

I followed all the naming rules written there [https://pythonrepo.com/repo/Solseum-solseum-nft-generator-python-miscellaneous#issues](url)

![Screenshot (83)](https://user-images.githubusercontent.com/72082971/149618704-11eeb174-399b-4c4a-82b4-2808b9ea7b0e.png)
![Screenshot (82)](https://user-images.githubusercontent.com/72082971/149618706-002f44a9-bff5-482e-b493-58eb075e2ae9.png)

**Comment by EclipseOfficeTech** [comment]
One of your images in one of your folders is not the same size.

Every image in your project have to be exactly the same size

**Comment by lucastoian** [comment]
they have all the same size, I checked
