### ISSUE TITLE
Enhancement: IPFS Support

### ISSUE THREAD

**Issue by LiamKenyon** [Solseum/solseum-nft-generator#3]
Would love the ability for IPFS support.

-- Pinata Cloud
-- NFT.Storage

Etc...

**Comment by Solseum** [comment]
https://github.com/Solseum/solseum-nft-generator/blob/main/includes/nft_creator.py#L179

You can create a new line down there that is something like **nftMetadata["image"] = "YOUR_NEW_IMAGE_PATH/"+str(nftsCounterThisRun+1)+".png"**

If you have a link that isn't mutable, with a common prefix you can set it on the template.json and do something like this
**nftMetadata["image"] += str(nftsCounterThisRun+1)+".png"**
