### ISSUE TITLE
Ranking

### ISSUE THREAD

**Issue by LiamKenyon** [Solseum/solseum-nft-generator#4]
Hello, first all thanks for the tool and also the rarity output saves a lot of time.

I'm wondering if you could also spit out a ranking also? 

For Example:

```
{
        "background": "item",
        "environment": "item",
        "body": "item",
        "eyes": "Stare",
        ......
        "rarityScore": 112.16,
        "name": "NFT#0001",
        "metadata": "1.json",
        "image": "1.png",
        "ranking": "1000"
    }
```

Hopefully that makes sense.

**Comment by Solseum** [comment]
Chad chad! Hello.

The rarity system will be implemente!! We already have in mind that, but we dont have to many time to keep adding features cause we are working on our AR app. The rarities will be includes when we creates our NFTs!
