### ISSUE TITLE
Possible to bypass a certain trait?

### ISSUE THREAD

**Issue by tpalaz** [Solseum/solseum-nft-generator#6]
Wondering if it's possible to bypass a certain trait?

Iv'e tried modifying the loop in CreateNfts but was unable to have certain attributes skipped if another was detected

**Comment by Solseum** [comment]
Its possible but we aren focussing on update the code ATM. Try using some data structures like a dict/map where the key is the item that you want and the values are a list with rejected items. So basically you check every time your dict/map if the item that you choose has some rejected items
