### ISSUE TITLE
Sub 1% traits

### ISSUE THREAD

**Issue by tpalaz** [Solseum/solseum-nft-generator#7]
Hello there,

With the current naming schema of traits (1-XXX.png), etc. Is it possible to generate a  < 1% trait - for example a 0.5% chance would be (05-XXX.png). Based on my testing the results I saw did not indicate that the 0 was taken into consideration, and the program saw this as a 5% trait. 

Thanks!

**Comment by Solseum** [comment]
Hello!!

The actual number system works! Maybe we miss explained in the guide and we are sorry for that!

The naming schema of NUMBER-XXX.png goes as following:
1. NUMBER is the number of times that that item should appear in the collection when you have a sample of (SUM of all NUMBERS in that trait) 

In the guide we say that is good set the sum up to 100 so you can have a percentage. You can set the sum up to whatever you want!

When you set the sum up to 100 thats means that the item should appear NUMBER times in 100 NFTs created.

The recommended way atm is setting the sum up to the number of NFTs and finally the NUMBER will mean that should appear that NUMBER times in the entire NFT collection, in that way you will have sub 1 rarity!

Lmk if this helps! I will leave this open so you can update me 🫂

**Comment by tpalaz** [comment]
ok that makes a lot more sense! I was basing this solely off percentages.

I appreciate the swift response :)

**Comment by Solseum** [comment]
Yeah is a better way that it was working always.

So I will drop an example to show that will work.

Imagine you have an 10000 NFT collection and you have your eyes attribute with 5 items as following. 
1. 10-Laser.png
2. 90-Rainbow.png
3. 1000-VR_headset.png
4. 3900-blue_eyes.png
5. 5000-confusion.png

The sum of all items is 10000 and each item should appear 10, 90, 1000, 3900 and 5000 times in your 10k collection (is random so you will have more or less). So imagine that the items appear that number of times and the final percentage of each items goes as follow:
1. 0.1% ((10*100)/10000)
2. 0.9% ((90*100)/10000)
3. 10% ((1000*100)/10000)
4. 39% ((3900*100)/10000)
5. 50% ((5000*100)/10000)

We hope this example works for everyone else with this issue! Cheers and good luck💎❤️🫂
